service: dynamodb-process-metadata

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.7
  memorySize: 512
  timeout: 600
  architecture: x86_64

  stackTags:
    product: soumil
    env: qa
    created-date: 2022-04-26
    team: python-dev
    customer-impact: false
    terraform: false

useDotenv: true


functions:
  lambda:
    handler: lambda_function.lambda_handler
    environment:
      DEV_AWS_ACCESS_KEY: ${env:AWS_ACCESS_KEY}
      DEV_AWS_SECRET_KEY: ${env:AWS_SECRET_KEY}
      DEV_AWS_REGION_NAME: ${env:AWS_REGION}
      TopicArn: arn:aws:sns:us-east-1:${env:ACCOUNT}:${env:TopicName}

    events:
      - stream:
          type: kinesis
          arn:
            Fn::GetAtt:
              - KinesisDataStreams
              - Arn

resources:

  Resources:
    SNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${env:TopicName}

    MySubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: shahsoumil519@gmail.com
        Protocol: email
        TopicArn: !Ref 'SNSTopic'

    myTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
          - AttributeName: gs1_process
            AttributeType: S
          - AttributeName: gsi_date_month
            AttributeType: S
          - AttributeName: gsi_date_day
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableClass: STANDARD
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: false
        GlobalSecondaryIndexes:
          - IndexName: ${env:GS1_INDEX}
            KeySchema:
              -
                AttributeName: "gs1_process"
                KeyType: "HASH"
              -
                AttributeName: "pk"
                KeyType: "RANGE"
            Projection:
              ProjectionType: ALL
          - IndexName: ${env:GS2_DAY_INDEX}
            KeySchema:
              -
                AttributeName: "gsi_date_day"
                KeyType: "HASH"
              -
                AttributeName: "pk"
                KeyType: "RANGE"
            Projection:
              ProjectionType: ALL
          - IndexName: ${env:GSI_MONTH_INDEX}
            KeySchema:
              -
                AttributeName: "gsi_date_month"
                KeyType: "HASH"
              -
                AttributeName: "pk"
                KeyType: "RANGE"
            Projection:
              ProjectionType: ALL
        KinesisStreamSpecification:
          StreamArn: !GetAtt KinesisDataStreams.Arn
        Tags:
          - Key: 'product'
            Value: 'soumil'
          - Key: 'customerImpact'
            Value: 'false'

    KinesisDataStreams:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: ${env:StreamName}
        RetentionPeriodHours: ${env:RetentionPeriodHours}
        StreamModeDetails:
          StreamMode: ON_DEMAND